---
services:
  jedi:
    build:
      context: .
      network: host
      target: backend-uncompressed
    network_mode: host
    environment:
      APP_NAME: JEDI Local
      APP_ENV: local
      APP_DEBUG: true
      APP_LOG_LEVEL: debug
      APP_URL: http://127.0.0.1:8000
      LOG_CHANNEL: stderr
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/storage/empty.sqlite
      BROADCAST_CONNECTION: log
      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      CAS_MASQUERADE: ltesting3
      CAS_HOSTNAME: sso-test.gatech.edu
      CAS_REAL_HOSTS: sso-test.gatech.edu
      CAS_CLIENT_SERVICE: http://127.0.0.1:8000
      CAS_LOGOUT_URL: http://127.0.0.1:8000
      SCOUT_DRIVER: collection
      MAIL_MAILER: log
    command: >-
      /bin/sh -euxc "export APP_KEY=$$(php artisan key:generate --show --verbose) &&
      touch $${DB_DATABASE} &&
      php artisan migrate --no-interaction &&
      php artisan tinker --no-interaction --verbose --execute \"\\App\\Models\\User::upsert(['username' => 'ltesting3', 'admin' => true], uniqueBy: ['username'], update: ['admin']); echo \\App\\Models\\User::where('username', '=', 'ltesting3')->sole()->createToken('local testing')->plainTextToken;\" &&
      exec php artisan serve"
